---
# === Domains ===
domain_main: getsimplicity.dev
domain_ai:   ai.getsimplicity.dev

# === Let's Encrypt ===
le_email: tech@simplicity.online

# === Samba ===
share_group: samba_share
samba_www_share_path: /var/www
samba_fileserver_share_path: /srv/fileserver

